### ISSUE TITLE
how fix it?

### ISSUE THREAD

**Issue by BlAd373** [apurvsinghgautam/dark-web-osint-tools#4]
Traceback (most recent call last):
  File "/home/Desktop/tools/VigilantOnion/observer.py", line 261, in <module>
    VigilantOnion().start
  File "/home/Desktop/tools/VigilantOnion/observer.py", line 168, in start
    geturls = Reddit().start
  File "/home/Desktop/tools/VigilantOnion/utils/engines/reddit.py", line 40, in start
    self.reddit_json()
  File "/home/Desktop/tools/VigilantOnion/utils/engines/reddit.py", line 52, in reddit_json
    for data in loaded_json['data']:
KeyError: 'data'

**Comment by apurvsinghgautam** [comment]
You should try printing "loaded_json" to see what it contains and whether it has 'data' key or not. Also, for further queries, you can directly put this in VigilantOnion github repo (https://github.com/andreyglauzer/VigilantOnion/issues)
